application: nyumafiagame
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*/lib/ionic
  static_dir: www/lib/ionic

- url: .*/css
  static_dir: www/css

- url: .*/js
  static_dir: www/js

- url: .*/img
  static_dir: www/img

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: latest
- name: jinja2
  version: latest
